---
- name: Ubuntu zero configuraion
  hosts: all
  roles:
    - {role: common, tags: ['desktop', 'laptop', 'server' , 'windows']}
    - {role: docker, tags: ['server']}
    - {role: laptop, tags: ['laptop']}
    - {role: set-apt-source, tags: ['desktop', 'laptop', 'server', 'windows']}
    - {role: ssh, tags: ['server']}
