---
- name: Ubuntu zero configuraion
  hosts: all
  roles:
     - {role: common, tags: ['desktop', 'laptop', 'server']}
     - {role: client, tags: ['desktop', 'laptop']}
     - {role: laptop, tags: ['laptop']}
     - {role: server, tags: ['server']}
