---

  - name: Add key
    apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present
    become: yes

  - name: Add repostitory of Node {{ node_version }}
    apt_repository:
      repo: deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_lsb.codename|lower }} main
      state: present
      filename: node
    become: yes

  - name: Upgrade packages
    apt:
      upgrade: yes
      update_cache: yes
      force: yes
      state: present
    become: yes

  - name: Install Node
    apt:
      name: nodejs
      force: yes
      state: present
    become: yes