---
  - name
  - name: Set bash colors
    replace:
       dest: ~/.bashrc
       regexp: '#force_color_prompt=yes'
       replace: 'force_color_prompt=yes'

  - name: Turn apport off
    replace:
       dest: /etc/default/apport
       regexp: 'enabled=1'
       replace: 'enabled=0'
    become: true

  - name: Copy template file
    templates:
    template:
      src: sources.list
      dest: /etc/apt/sources.list

  - name: Add Java repository to sources
    apt_repository:
      repo: 'ppa:webupd8team/java'
    become: true

  - name: Autoaccept license for Java
    shell: echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
    become: true

  - name: Upgrade packages
    apt:
      upgrade: yes
      update_cache: yes
      force: yes
      state: present
    become: true

  - name: Install packages
    apt:
      name: "{{item}}"
      force: yes
      state: present
    become: true
    with_items:
      - preload
      - gimp
      - skype
      - chromium-browser
      - gthumb
      - rar
      - unrar
      - bmon
      - htop
      - tmux
      - guake
      - iotop
      - cpufrequtils
      - lm-sensors
      - trash-cli
      - gnome-system-monitor
      - gparted
      - oracle-java8-installer