---
  - name: Set bash colors
    replace:
       dest: "{{ item }}"
       regexp: '#force_color_prompt=yes'
       replace: 'force_color_prompt=yes'
    become: yes
    with_items:
       - "/root/.bashrc"
       - "/home/{{ ansible_user_id }}/.bashrc"

  - name: Turn apport off
    replace:
       dest: /etc/default/apport
       regexp: 'enabled=1'
       replace: 'enabled=0'
    become: yes

  - name: Install packages
    apt:
      name: "{{item}}"
      force: yes
      state: present
    become: yes
    with_items:
      - preload
      - rar
      - unrar
      - bmon
      - htop
      - tmux
      - guake
      - iotop
      - cpufrequtils
      - lm-sensors
      - trash-cli
