---
  - name: Setup arch
    lineinfile:
      dest: '/var/lib/dpkg/arch'
      line: "{{ item }}"
      create: yes
    become: yes
    with_items:
      - amd64
      - i386

  - name: Upgrade packages
    apt:
      upgrade: yes
      update_cache: yes
      force: yes
      state: present
    become: yes

  - name: Install packages
    apt:
      name: "{{item}}"
      force: yes
      state: present
    become: yes
    with_items:
        - gimp
        - skype
        - chromium-browser
        - gthumb
        - gnome-system-monitor
        - gparted